### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jerome8946** [senzhk/ADBKeyBoard#10]
window7    adnroid   phone:SM-N9006   4.4.2
adb shell am broadcast -a ADB_INPUT_TEXT --es msg '你好嗎? Hello?'

WARNING:linker:app_process has text relocations.This is wasting menory and is a security risk.Please fix.
Broadcasting: Intent { act=ADB_INPUT_TEXT (has extras) } Broadcast completed: result=0 

EditText  There is no value

**Comment by eggcaker** [comment]
same here

**Comment by ngochoaitn** [comment]
You must set ADB Keyboad as default input method and turn of physical keyboard in Setting.

**Comment by sougannkyou** [comment]
设置默认输入为adbkeyboard并且关闭物理键盘开关

**Comment by lovelyplanet2019** [comment]
i have turned off all keyboard and left only ADB keyboard. at cmd 
adb shell am broadcast -a ADB_INPUT_TEXT --es msg '你好嗎? Hello?'
Broadcasting: Intent { act=ADB_INPUT_TEXT flg=0x400000 (has extras) }
Broadcast completed: result=0
