### ISSUE TITLE
How to download APK?

### ISSUE THREAD

**Issue by tomaszs** [senzhk/ADBKeyBoard#11]
I've reformated my device. Anyone have APK? 

IT was here before:
https://github.com/senzhk/ADBKeyBoard/blob/master/bin/ADBKeyBoard.apk

**Comment by jiru** [comment]
Apparently it’s been removed in a later commit but you can still [browse history](https://github.com/senzhk/ADBKeyBoard/blob/758dab32cb220ffbf4bd1a2a58338c8948c86a63/bin/ADBKeyBoard.apk).

**Comment by marmistrz** [comment]
@tomaszs you can use the F-Droid buil
