### ISSUE TITLE
不支持中文输入

### ISSUE THREAD

**Issue by 37du** [senzhk/ADBKeyBoard#13]
使用 adb shell am broadcast -a ADB_INPUT_TEXT --es msg '你好嗎? Hello?'  ， 无法显示， 如果是adb shell am broadcast -a ADB_INPUT_TEXT --es msg 'Hello?'就可以显示

模拟器使用 Android O

**Comment by lochen8** [comment]
我的是发送中文出现乱码 你的解决了吗

**Comment by LeeFo-china** [comment]
C:\Users\LeeFo\IdeaProjects\MyApplication3>adb shell am broadcast -a ADB_INPUT_B64 --es ms
g echo '你好嗎? Hello?' | base64
'base64' is not recognized as an internal or external command,
operable program or batch file.
