### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by jidanni** [senzhk/ADBKeyBoard#2]
We want to input Chinese in Android Emulator.

We download this zip file.

But inside it all we find is a README.md which doesn't say where we are supposed to put the zip etc. etc.

**Comment by mickhansen** [comment]
+1 A downloadable .apk would help onboarding a great deal i imagine.

**Comment by senzhk** [comment]
oh, I found out I accidentally committed a debug apk file : https://github.com/senzhk/ADBKeyBoard/blob/master/bin/ADBKeyBoard.apk
