### ISSUE TITLE
adb shell am broadcast -a ADB_INPUT_TEXT --es msg for hebrew chars

### ISSUE THREAD

**Issue by michaazran** [senzhk/ADBKeyBoard#23]
hi

i am trying  to use the keyboard to send hebrew characters to my mobile
adb shell am broadcast -a ADB_INPUT_TEXT --es msg 'HEBREW WORD'

but it is not running, when i use
am broadcast -a ADB_INPUT_CHARS --eia chars '1502,1497,1499,1488,1500'
it is working successfully 

any idea ?

**Comment by senzhk** [comment]
Latest Android doesn't allow sending these via command line,

1.1 Sending text input (base64) if (1) is not working.
adb shell am broadcast -a ADB_INPUT_B64 --es msg `echo '你好嗎? Hello?' |
base64`

**Comment by michaazran** [comment]
so ADB_INPUT_CHARS is the only way to use it ?

**Comment by senzhk** [comment]
No, you can use the "base64" tool :

adb shell am broadcast -a ADB_INPUT_B64 --es msg `echo 'HEBREW WORD' |
base64`

**Comment by michaazran** [comment]
not working
it send other characters and not my Hebrew characters

**Comment by michaazran** [comment]
by the way, when i send English characters using the base64 the keyboard crush, i am getting a message "unfortunately ADBKeyboard has stopped"
