### ISSUE TITLE
ADBKeyboard not reflecting my text after i change the keyboard

### ISSUE THREAD

**Issue by michaazran** [senzhk/ADBKeyBoard#24]
hi

i have the following scenario:
i am using my regular samsung keyboard
from adb shell i change the keyboard and type text and nothing happened, ONLY when i manually tap the editbox i get a message of ADB Keyboard{ON} and only now i can send the keys
it's like changing the keyboard is not enough , you should also operate it somehow
is there a way to avoid it? i need to run it without manual intervention ???

thanks.

ime set com.android.adbkeyboard/.AdbIME   
am broadcast -a ADB_INPUT_TEXT --es msg 'test'

**Comment by sjlnl** [comment]
I have the same problem. Have you solved this problem

**Comment by sjlnl** [comment]
I have the same problem. Have you solved this problem
