### ISSUE TITLE
use adb shell am broadcast -a ADB_INPUT_B64 --es msg `echo '你好嗎? Hello?' | base64` will generate space after string

### ISSUE THREAD

**Issue by luisxiaomai** [senzhk/ADBKeyBoard#31]
As title, input chinese use base64 way will generate space after sting.

**Comment by senzhk** [comment]
you are right, echo issue, this should fix:

adb shell am broadcast -a ADB_INPUT_B64 --es msg `echo -n '你好嗎? Hello?' |
base64`
