### ISSUE TITLE
i create a script to paste content from windows to android base on this project

### ISSUE THREAD

**Issue by ssddi456** [senzhk/ADBKeyBoard#33]
the script can get from [here](https://gist.github.com/ssddi456/889d5e8a2571a33e8fcd0ff6f1288291)

1.  install adbkeyboard on your phone
1. download the scripts and add it to your path,
1. connect to your phone with adb
1. when you want to paste content ,just run adbpaste

the ones who cannot execute ps1 scripts can resolve it [here](https://stackoverflow.com/questions/4037939/powershell-says-execution-of-scripts-is-disabled-on-this-system)

**Comment by senzhk** [comment]
Cool. Thanks. Added in README>

**Comment by sunshinewithmoonlight** [comment]
Hello, I have a python script that implements the same function as your ps script. :3

import os
import base64

# os.system("adb devices")

chars = '的广告'
charsb64 = str(base64.b64encode(chars.encode('utf-8')))[1:]
# print(charsb64)

os.system("adb shell am broadcast -a ADB_INPUT_B64 --es msg %s" %charsb64)
Thanks to https://stackoverflow.com/questions/33294213/how-to-decode-unicode-in-a-chinese-text

**Comment by senzhk** [comment]
Thanks.
