### ISSUE TITLE
how to input quotes and double quotes?

### ISSUE THREAD

**Issue by amoxuk** [senzhk/ADBKeyBoard#34]
I try to input the test text 
`adb shell "am broadcast -a ADB_INPUT_TEXT --es msg '中文输入test'"`
perfected on python script by `decode('utf-8').encode('utf-8')`!
but when I want input a qoutes or double quotes, it runs failed.
FAIL:
`adb shell "am broadcast -a ADB_INPUT_TEXT --es msg '中文\'输入test'"`
or 
`adb shell "am broadcast -a ADB_INPUT_TEXT --es msg '中文\"输入test'"`
or
`adb shell "am broadcast -a ADB_INPUT_TEXT --es msg '中文\\"输入test'"`
return `/system/bin/sh: no closing quote`

so, how to input quotes and double quotes by comand line or python?

**Comment by senzhk** [comment]
I think you better try the latest base64 wrapper:

1.1 Sending text input (base64) if (1) is not working.

* For Mac/Linux, you can use the latest base64 input type with base64 command line tool:
adb shell am broadcast -a ADB_INPUT_B64 --es msg `echo '你好嗎? Hello?' | base64`

* For Windows, please try this script (provided by ssddi456): 
https://gist.github.com/ssddi456/889d5e8a2571a33e8fcd0ff6f1288291
