### ISSUE TITLE
Is it possible to clear focused input text using adbkeyboard? 

### ISSUE THREAD

**Issue by oleksiivasylenko** [senzhk/ADBKeyBoard#37]
Currently there is no normal way to clear text of focused android input.
Is it possible to use this keyboard for cleaning input?

**Comment by senzhk** [comment]
I believe you can send "CTRL+A" and "DELETE" keyevent using:

2. Sending keyevent code  (67 = KEYCODE_DEL) in README

OR you can send out fair amount of DEL key.

Currently we don't support this feature on the keyboard, but nice to add it later.

**Comment by senzhk** [comment]
also CTRL+A is easy as well:

5. Send meta keys
To send Ctrl+Space
adb shell am broadcast -a ADB_INPUT_MCODE --eia mcode '4096,62'

**Comment by oleksiivasylenko** [comment]
Hi @senzhk 

I've tried your code `adb shell am broadcast -a ADB_INPUT_MCODE --eia mcode '4096,62'`
and nothing happened.
Also I've tried `4096,29`, 29 is `KEYCODE_A` according to this [link](https://gist.github.com/Pulimet/5013acf2cd5b28e55036c82c91bd56d8)

[video](https://youtu.be/w2Ivg81JTSQ)
Please tell me if I understand it right? Or I'am doing something wrong.

**Comment by senzhk** [comment]
The apk in the github is old, so I think it should not support ADB_INPUT_MCODE
yet.
Please consider compiling the apk yourself.

**Comment by oleksiivasylenko** [comment]
@senzhk, thank you for suggestion. 
I've just compiled but it's still nothing happened after sending mcode, do you have any ideas what else might be wrong?

**Comment by senzhk** [comment]
added a new command


6. CLEAR all text (starting from v2.0)
adb shell am broadcast -a ADB_CLEAR_TEXT

also uploaded the latest apk in the root directory.
