### ISSUE TITLE
ADB_INPUT_B64 seems not working now

### ISSUE THREAD

**Issue by 0v0** [senzhk/ADBKeyBoard#39]
As tested on my latest device, this broadcast seems not working.

But ADB_INPUT_TEXT works for Ascii letters.

So I cannot input unicode characters by now.

**Comment by senzhk** [comment]
I tested again with the apk in the latest build, 

adb shell am broadcast -a ADB_INPUT_B64 --es msg `echo -n '你好嗎? Hello?' | base64`

it works on my device (Android Q)

Please provide more information.

**Comment by senzhk** [comment]
it works on Android R too. (verified)

**Comment by 0v0** [comment]
> it works on Android R too. (verified)

Thank you for the reply. I found the failure resulted from the adbutils policy on parsing parameter in `shell` method. It has a special handling on non-ascii characters.

**Comment by senzhk** [comment]
ic, I never use any python library, so please try using adb shell in console.
