### ISSUE TITLE
How about candidate text input?

### ISSUE THREAD

**Issue by PonyPC** [senzhk/ADBKeyBoard#40]
While using IME in typing Japanese or Chinese, there is a candidate text with underline in input box.
Could you please implement this feature for scrcpy users? Thanks.

**Comment by senzhk** [comment]
if you select ADBkeyboard in the input method, you will not see the "candidate" text, because ADBkeyboard itself didn't provide.

Also, the primary focus for this keyboard is mainly for testing purpose, that means you know what you have to input but not necessary to select "candidate" text.
