### ISSUE TITLE
Work on Android 10/11?

### ISSUE THREAD

**Issue by rubikitch** [senzhk/ADBKeyBoard#42]
I use ADBKeyBoard on Android 9.
It works very nice! Thanks.

Does ADBKeyBoard work on Android 10/11?

**Comment by oneornone** [comment]
> I use ADBKeyBoard on Android 9.
> It works very nice! Thanks.
> 
> Does ADBKeyBoard work on Android 10/11?

Yes, I've tried it on MI8SE(Android 10) and it worked well.

**Comment by rubikitch** [comment]
Thanks!
