### ISSUE TITLE
how can send alt +v or other win+v 

### ISSUE THREAD

**Issue by xxdoc** [senzhk/ADBKeyBoard#47]
To send Ctrl+Space
adb shell am broadcast -a ADB_INPUT_MCODE --eia mcode '4096,62'

what is 4096?

**Comment by senzhk** [comment]
https://developer.android.com/reference/android/view/KeyEvent

You should able to find it in here, with keyword 4096

**Comment by xxdoc** [comment]
how can send alt +v or other win+v
