### ISSUE TITLE
enable failed

### ISSUE THREAD

**Issue by Jerrywang77** [senzhk/ADBKeyBoard#66]
Enable prompt for unknown input method after keyboard installation：
Unknown input method com.android.adbkeyboard/.AdbIME cannot be selected for user #0
for Android 14

**Comment by chrisgeli** [comment]
Same issue here. I installed it via `adb install ADBKeyboard.apk` and then listed the available input methods:
```
$ adb shell ime list -s
com.android.inputmethod.latin/.LatinIME
com.volosyukivan/.WiFiInputMethod
```
i.e. the .AdbIME doesn't show up.

Unsurprisingly, 
```
$ adb shell ime set com.android.adbkeyboard/.AdbIME
Unknown input method com.android.adbkeyboard/.AdbIME cannot be selected for user #0
```
the input method isn't available.

For now I've been working with `com.volosyukivan/.WiFiInputMethod` which should have all available features, but I'd like to see if `com.android.adbkeyboard/.AdbIME` is easier, which I think it should be as I don't have to talk to it via HTTP and don't need to forward ports.

**Comment by senzhk** [comment]
not sure if it related to sdk version, but just uploaded a new apk with newer api.
```
adb shell ime list -s
 - com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
- com.android.adbkeyboard/.AdbIME

adb shell ime enable com.android.adbkeyboard/.AdbIME

adb shell ime set com.android.adbkeyboard/.AdbIME
```

**Comment by chrisgeli** [comment]
Thanks for the update @senzhk . Maybe the problem wasn't related to the API at all, but with the order of `adb` commands:

```
$ adb install ADBKeyboard.apk 
Performing Streamed Install
Success
$ adb shell ime list -s
com.android.inputmethod.latin/.LatinIME
com.volosyukivan/.WiFiInputMethod
$ adb shell ime enable com.android.adbkeyboard/.AdbIME
Input method com.android.adbkeyboard/.AdbIME: now enabled for user #0
$ adb shell ime list -s
com.android.inputmethod.latin/.LatinIME
com.volosyukivan/.WiFiInputMethod
com.android.adbkeyboard/.AdbIME
```

As you can see, even after installing the new apk, the ime list still didn't show the `AdbIME` entry. Only after `ime enable` it became visible in `ime list` and I was able to

```
$ adb shell ime set com.android.adbkeyboard/.AdbIME
Input method com.android.adbkeyboard/.AdbIME selected for user #0
```

Maybe this helps you as well, @Jerrywang77 .

**Comment by senzhk** [comment]
add to README.
