### ISSUE TITLE
whaaa??

### ISSUE THREAD

**Issue by CamsShaft** [senzhk/ADBKeyBoard#70]
This is a new one for me... tried to install this and didn't install properly (just didn't want to open) so I uninstalled it,  I thought I did anyways. I wanted to try it again and nope, it's apparently still installed and won't allow me to "update" it. I've looked everywhere, it's not in user apps or system apps somehow, it's not invisible or unlabeled. A true wtf moment for me. I'll try adb and see if I get anywhere with that and if not then I dunno :\

**Comment by CamsShaft** [comment]
Okay, this is starting to bug me. This app may have broken something. This app is non-existant according to everything I've tried. Too bad samsung are pieces of garbage and won't allow me to root this thing. I have exhausted everything I know and can't find it anywhere in my system.

**Comment by senzhk** [comment]
at first, you said it didn't install and then you cannot uninstall? that's very strange. Let's assume you didn't change the package name.

what did you see when you run the following adb command:

adb shell dumpsys package com.android.adbkeyboard

**Comment by CamsShaft** [comment]
Sorry for the wait. I completely forgot I installed it with a platform signature I forgot to turn off in app manager. Still, I've never seen this before. Wasn't blaming you either, I honestly forgot about the signature...


![Screenshot_20240224_201120_Termux](https://github.com/senzhk/ADBKeyBoard/assets/141678661/1a83a8c8-f6f6-4ee7-92fd-a5229c48fa43)

**Comment by senzhk** [comment]
ic, it is not a system app either, so I am not sure why you cannot install. Using platform sig is rare.

nevermind, can you do this
adb shell pm disable com.android.adbkeyboard
adb shell uninstall com.android.adbkeyboard

**Comment by CamsShaft** [comment]
It didn't like the disable command but uninstall worked! Pretty simple after all haha. Yeah I managed to find the sig on github and thought it would be a great idea to try getting some extra privileges. Shizuku has given me a taste and now I want more, what can I say?
