### ISSUE TITLE
请问如何发送回车键？

### ISSUE THREAD

**Issue by zw963** [senzhk/ADBKeyBoard#8]
例如，我希望打一段中文，然后，立刻从 android 的 QQ 的聊天窗口发出去。

我有这样一个 bash 函数:

```sh
function adb_key () {
    adb shell am broadcast -a ADB_INPUT_TEXT --es msg "$*\n"
}
```

这里的 \n 似乎是无效的, 发了个 \n 到 QQ, 而不是回车。

**Comment by tkggusraqk** [comment]
兄弟，你的能输入中文吗，我测试 的怎么是乱码呀

**Comment by senzhk** [comment]
可以的 我是用中文試的啦。

**Comment by zw963** [comment]
@tkggusraqk , 简单的中文没问题，不过有时候会失败，可能包含了一些特殊的标点符号，当时在聊天，没有记录下来。

@senzhk , 你咋不回复偶的问题呐？ 谢谢。

**Comment by tkggusraqk** [comment]
@zw963 @senzhk 我的是一般的中文都不行呀，这里没办法发图，我的qq号：576501565，希望两位大神能不吝赐教

**Comment by zw963** [comment]
@tkggusraqk ,  你需要去设定里面激活 ADBKeyBoard 作为当前输入法。

如果不知道在那里设定，你可以装个搜狗， 它自己带了个输入法设定工具。

@senzhk , 为啥不回复我的问题？ 支应一声？

**Comment by senzhk** [comment]
@Billy 你说是\n 的问题，那我在README有写 \n 是特别键来的，要用CODE 来发，当然你可以把代码改成认\n 也可以。

Regards,
Eric

2016-04-26 22:13 GMT+08:00 Billy <notifications@github.com>:

**Comment by zw963** [comment]
> @Billy 你说是\n 的问题，那我在README有写 \n 是特别键来的，要用CODE 来发，当然你可以把代码改成认\n 也可以。

谢谢， 刚刚注意到 README 有提及特殊字符。

不过没有提及 `\n` ?? 我看到 `67 = KEYCODE_DEL`,
这个 67, 貌似不是我知道的任何表。

我到那里去查看  `\n` 的数字？ 

谢。

**Comment by senzhk** [comment]
@Billy
http://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_ENTER


Regards,
Eric

2016-04-27 0:00 GMT+08:00 Billy <notifications@github.com>:

**Comment by zw963** [comment]
已试可用， 回车键是 66, 谢谢。

**Comment by zw963** [comment]
在我手机上， QQ 轻聊版不可用， 应该是 app 的问题。
但是， 微信可用。 聊天省事儿多了。

**Comment by tkggusraqk** [comment]
@zw963 我设置了，还是不起作用，你加我qq：576501565

**Comment by tkggusraqk** [comment]
@senzhk  我的是windows 系统 用adb 连接 命令行调试，确实不行呀，接收到的是乱码
我用android studio 调试看了，中文收到的就是乱码。怎么解决呢，很着急，求大神赐教一下，我qq:576501565

**Comment by zw963** [comment]
我几乎不上 QQ 啊。
再说， Windows 下我也帮不到你了， 我没在 Windows 下用过 adb.

我怀疑是你发送的字符采用的编码是 GBK, 而不是 Linux 默认支持的 UTF-8.
你你可以 Google 下 adb 编码的问题。

**Comment by zw963** [comment]
或者问下作者，编码支持是不是加个啥参数就可以了。

**Comment by tkggusraqk** [comment]
@zw963 我已经解决了，我也没有去解决编码问题，我是直接把要传输的内容转换成字节 ，然后再还原。
@senzhk 谢谢提供的这个keyborad

**Comment by colordancer** [comment]
@tkggusraqk 怎么解决的？能否贴段代码？
这里也看到有人和你问一样的问题：http://smilejay.com/2014/12/adb-shell-input-chinese-character/
